In [38]:
import numpy as np

In [39]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.array([[1,5],[2,4]])

### Addition

**Cummulative**


In [40]:
# A + B
np.add(A,B)

array([[ 6,  8],
       [10, 12]])

In [41]:
# B + A
np.add(B,A)

array([[ 6,  8],
       [10, 12]])

**Associative**

In [42]:
# ( A + B) + C
np.add(np.add(A,B), C)

array([[ 7, 13],
       [12, 16]])

In [43]:
# A + (B + C)
np.add(A, np.add(B,C))

array([[ 7, 13],
       [12, 16]])

### Multiplication

**Associative**

In [44]:
# (A * B) * C
np.matmul(np.matmul(A,B), C)

array([[ 63, 183],
       [143, 415]])

In [45]:
# A * (B * C)
np.matmul(A, np.matmul(B,C))

array([[ 63, 183],
       [143, 415]])

**Distributive**

In [46]:
# A * (B + C)
np.matmul(A, np.add(B,C))

array([[24, 35],
       [54, 81]])

In [47]:
# A * B + A * C
np.add(np.matmul(A,B), np.matmul(A,C))

array([[24, 35],
       [54, 81]])

**Not Cummulative**

In [48]:
# A * B
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [49]:
# B * A
np.matmul(B,A)

array([[23, 34],
       [31, 46]])